[package]
name = "bismuth-lexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bismuth-md = {version = "0.1.0", path = "../bismuth-md"}
regex = "1"

[dev-dependencies]
insta = "1.26.0"
